# Generated by Django 4.2.30 on 2026-05-22 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女"), ("other", "其他")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="年龄"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("high_school", "高中"),
                            ("associate", "大专"),
                            ("bachelor", "本科"),
                            ("master", "硕士"),
                            ("phd", "博士"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="学历",
                    ),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=200, verbose_name="毕业院校"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "work_experience_years",
                    models.PositiveIntegerField(default=0, verbose_name="工作年限"),
                ),
                (
                    "current_company",
                    models.CharField(blank=True, max_length=200, verbose_name="当前公司"),
                ),
                (
                    "current_position",
                    models.CharField(blank=True, max_length=200, verbose_name="当前职位"),
                ),
                ("resume_url", models.URLField(blank=True, verbose_name="简历链接")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "候选人",
                "verbose_name_plural": "候选人",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "total_referrals",
                    models.PositiveIntegerField(default=0, verbose_name="总推荐数"),
                ),
                (
                    "new_referrals",
                    models.PositiveIntegerField(default=0, verbose_name="新增推荐数"),
                ),
                (
                    "hired_count",
                    models.PositiveIntegerField(default=0, verbose_name="入职人数"),
                ),
                (
                    "total_rewards",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="总奖励金额"
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="转化率(%)"
                    ),
                ),
                (
                    "avg_time_to_hire",
                    models.PositiveIntegerField(default=0, verbose_name="平均招聘周期(天)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "统计指标",
                "verbose_name_plural": "统计指标",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="部门名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="部门编码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="部门描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                        verbose_name="上级部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="岗位名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="岗位编码"),
                ),
                ("description", models.TextField(verbose_name="岗位描述")),
                ("requirements", models.TextField(verbose_name="任职要求")),
                ("responsibilities", models.TextField(verbose_name="工作职责")),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "全职"),
                            ("part_time", "兼职"),
                            ("intern", "实习"),
                            ("contract", "合同制"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="工作类型",
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="工作地点")),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="最低薪资",
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="最高薪资",
                    ),
                ),
                (
                    "headcount",
                    models.PositiveIntegerField(default=1, verbose_name="招聘人数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "开放"),
                            ("paused", "暂停"),
                            ("closed", "已关闭"),
                            ("filled", "已招满"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                        verbose_name="所属部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "岗位",
                "verbose_name_plural": "岗位",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(max_length=50, unique=True, verbose_name="内推编号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "已提交"),
                            ("screening", "筛选中"),
                            ("interviewing", "面试中"),
                            ("offer_sent", "已发Offer"),
                            ("offer_accepted", "已接受Offer"),
                            ("hired", "已入职"),
                            ("rejected", "已拒绝"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("internal", "内部员工"),
                            ("alumni", "校友推荐"),
                            ("partner", "合作伙伴"),
                            ("other", "其他"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="推荐来源",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=50, verbose_name="与候选人关系"),
                ),
                ("referrer_notes", models.TextField(blank=True, verbose_name="内推人备注")),
                ("hr_notes", models.TextField(blank=True, verbose_name="HR备注")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新"),
                ),
                (
                    "hired_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="入职时间"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="core.candidate",
                        verbose_name="候选人",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="core.position",
                        verbose_name="推荐岗位",
                    ),
                ),
            ],
            options={
                "verbose_name": "内推记录",
                "verbose_name_plural": "内推记录",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("fixed", "固定金额"),
                            ("percentage", "薪资百分比"),
                            ("tiered", "阶梯奖励"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="奖励类型",
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="固定金额",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="百分比(%)",
                    ),
                ),
                (
                    "min_reward",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="最低奖励",
                    ),
                ),
                (
                    "max_reward",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="最高奖励",
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("onboard", "入职时"),
                            ("probation_passed", "转正后"),
                            ("stay_3m", "满3个月"),
                            ("stay_6m", "满6个月"),
                            ("stay_1y", "满1年"),
                        ],
                        default="onboard",
                        max_length=20,
                        verbose_name="触发条件",
                    ),
                ),
                (
                    "delay_days",
                    models.PositiveIntegerField(
                        default=0, help_text="触发后延迟发放的天数", verbose_name="延迟天数"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "applicable_departments",
                    models.ManyToManyField(
                        blank=True, to="core.department", verbose_name="适用部门"
                    ),
                ),
                (
                    "applicable_positions",
                    models.ManyToManyField(
                        blank=True, to="core.position", verbose_name="适用岗位"
                    ),
                ),
            ],
            options={
                "verbose_name": "奖励规则",
                "verbose_name_plural": "奖励规则",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_code",
                    models.CharField(max_length=50, unique=True, verbose_name="奖励编号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="奖励金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发放"),
                            ("processing", "处理中"),
                            ("paid", "已发放"),
                            ("cancelled", "已取消"),
                            ("failed", "发放失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("salary", "工资发放"),
                            ("bonus", "奖金发放"),
                            ("gift_card", "礼品卡"),
                            ("cash", "现金"),
                            ("other", "其他"),
                        ],
                        default="salary",
                        max_length=20,
                        verbose_name="发放方式",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="发放日期"),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="支付参考号"),
                ),
                (
                    "tax_deducted",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="代扣税额"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="实发金额"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="实际发放时间"),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发放人",
                    ),
                ),
                (
                    "referral",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward",
                        to="core.referral",
                        verbose_name="内推记录",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.rewardrule",
                        verbose_name="奖励规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "奖励发放",
                "verbose_name_plural": "奖励发放",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referrer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=20, unique=True, verbose_name="工号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                (
                    "total_referrals",
                    models.PositiveIntegerField(default=0, verbose_name="总推荐数"),
                ),
                (
                    "successful_referrals",
                    models.PositiveIntegerField(default=0, verbose_name="成功推荐数"),
                ),
                (
                    "total_rewards",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="总奖励金额"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "内推人",
                "verbose_name_plural": "内推人",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted", "已提交"),
                            ("screening", "筛选中"),
                            ("interviewing", "面试中"),
                            ("offer_sent", "已发Offer"),
                            ("offer_accepted", "已接受Offer"),
                            ("hired", "已入职"),
                            ("rejected", "已拒绝"),
                            ("withdrawn", "已撤回"),
                        ],
                        max_length=20,
                        verbose_name="原状态",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("submitted", "已提交"),
                            ("screening", "筛选中"),
                            ("interviewing", "面试中"),
                            ("offer_sent", "已发Offer"),
                            ("offer_accepted", "已接受Offer"),
                            ("hired", "已入职"),
                            ("rejected", "已拒绝"),
                            ("withdrawn", "已撤回"),
                        ],
                        max_length=20,
                        verbose_name="新状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.referral",
                        verbose_name="内推记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "状态变更历史",
                "verbose_name_plural": "状态变更历史",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="referral",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="core.referrer",
                verbose_name="内推人",
            ),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "电话面试"),
                            ("video", "视频面试"),
                            ("onsite", "现场面试"),
                            ("technical", "技术面试"),
                            ("behavioral", "行为面试"),
                            ("final", "终面"),
                        ],
                        max_length=20,
                        verbose_name="面试类型",
                    ),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(default=1, verbose_name="轮次"),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="预约时间")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=60, verbose_name="预计时长(分钟)"),
                ),
                ("interviewer", models.CharField(max_length=100, verbose_name="面试官")),
                (
                    "interviewer_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="面试官邮箱"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="面试地点/链接"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "待定"),
                            ("passed", "通过"),
                            ("failed", "未通过"),
                            ("rescheduled", "改期"),
                            ("cancelled", "取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="面试结果",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="面试反馈")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="评分",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="core.referral",
                        verbose_name="内推记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试记录",
                "verbose_name_plural": "面试记录",
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
